# Lazypipe v3 config
# can include env vars

# GENERAL PARAMETERS
general.parameters:
   #call_R:                   "Rscript --no-save"
   call_R:                   "singularity_wrapper exec Rscript --no-save"
   min_read2hostgen_score:   100     # minimum alignment score for read mapping to hostgen
   min_read2hostgen_mapq:    0
   min_contig2hostgen_score: 300     # minimum alignment score for contig mapping to hostgen
   min_contig_length:        300
   min_orf_length:           72      # minimum ORF length in nucleotides
   min_sans_bits:            200     # minimum alignment score for orf mapping with SANS
   min_hmmscan_bits:         0
   max_hmmscan_eval:         0.01
   min_blastp_bits:          200     # minimum alignment score for orf mapping with BLASTP/X
   min_blastn_bits:          200     # minimum alignment score for contig mapping with blastn
   min_diamond_bits:         200
   min_minimap_DPpeak_score: 200     # minimum alignment score for contig mapping with minimap2
   min_read2contig_score:    80      # minimum alignment score for read mapping to contigs
   min_read2contig_mapq:     0       # minimum alignment quality for read mapping to contigs
   min_psearch_bits_abund:   200     # minimum prot search (eg blastp) bitscore in abundance estimation
   min_nsearch_bits_abund:   200     # minimum nucl search (eg minimap) bitscore in abundance estimation
   min_qcov_abund:           0.50    # minimum query coverage in abundance estimation
   min_qcov_annot:           0.20    # minimum query coverage in annotation reports
   par_trimm:                "ILLUMINACLIP:$TM/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"
   par_fastp:                "-q 15 -u 40 -l 36 --detect_adapter_for_pe --cut_right --cut_window_size 4 --cut_mean_quality 15 --correction"
   refgenrep_min_clen_sum:   1000    # refgen report parameter, minimum contig length sum to report taxon
   refgenrep_min_alen_sum:   0       # refgen report parameter, minimum alignment length sum to report taxon
   refgenrep_max_refgen:     10      # refgen report parameter, maximum number of reference genomes per taxon
   par_megahit:              "--presets meta-sensitive"
   par_spades:               ""
   tail:                     0       # Remove taxa that correspond to this percentile in abundance estimation. Set to zero to keep all predictions.
   tail_contig:              5       # Remove taxa from contig that correspond to this percentile. Reduces noise in abundance estimation.
   taxgroups:                "all"   # taxgroups listed in abund_table.xlsx and annot_table.xlsx. Set to "all" to report all
   toptaxrank:               "division" # can be e.g. "division", "kingdom" or "superkingdom" when using old versions of NCBI taxonomy
   trimm_sample_name:        0       # when setting sample-name to read1-name, trimm sample-name to the first occurance of "_"


# DEFAULT COMMAND LINE OPTIONS
   # input:
#hostgen:            "$hostgenomes/GCA_000001405.15_GRCh38_genomic.fna"
hostgen:            0
hostgen_taxid:      0
   # output:
logs:               "logs"           # logs directory
res:                "$data/results"  # results directory
#tmpdir:             "$data/wrkdir"
tmpdir:             $LOCAL_SCRATCH/wrkdir
tmpdir_keep:        0
   # parameters
pipe:               "main"
pre:                "fastp"     # preprocess: fastp/trimm/none
ass:                "megahit"   # assembler: megahit/spades
ann1:               0
ann2:               0
anns:               0
gen:                "mga"       # gene prediction: mga/prod  (MetaGeneAnnotator/Prodigal)
wmodel:             "bitscore2"  # model for read abundance estimation: taxacount/bitscore/bitscore2
numth:              16
webmode:            0


# REFERENCE DATABASES FOR 1ST AND 2ND ROUND ANNOTATIONS
ann.databases:
   minimap.nt:
      db:      "$databases/nt.2025_01_12.fa"
      name:    "nt.2025_01_12.fa"
      search:  "minimap"
      url:     "NA"
   minimap.nt.abv:
      db:      "$databases/nt.abv.2025_01_12.fa"
      name:    "nt.abv.2025_01_12"
      search:  "minimap"
      url:     "https://a3s.fi/lazypipe-db/minimap.nt.abv.2025_01_12.tar.gz"
   minimap.nt.vi:
      db:      "$databases/nt.vi.2025_01_12.fa"
      name:    "nt.vi.2025_01_12"
      search:  "minimap"
      url:     "https://a3s.fi/lazypipe-db/minimap.nt.vi.2025_01_12.tar.gz"
   minimap.refseq.abv:
      db:      "$databases/refseq.abv.release228.fa"
      name:    "refseq.abv.release228"
      search:  "minimap"
      url:     "https://a3s.fi/lazypipe-db/minimap.refseq.abv.release228.tar.gz"
   minimap.refseq.vi:
      db:      "$databases/refseq.vi.release228.fa"
      name:    "refseq.vi.release228"
      search:  "minimap"
      url:     "https://a3s.fi/lazypipe-db/minimap.refseq.vi.release228.tar.gz"
   blastn.nt:
      db:     "$databases/blast/2025_01_12/nt"
      name:   "nt.2025_01_12"
      search: "blastn"
      url:    "NA"
   blastn.nt.abv:
      db:     "$databases/blastn.nt.abv.2025_01_12"
      name:   "nt.abv.2025_01_12"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.nt.abv.2025_01_12.tar.gz"
   blastn.nt.vi:
      db:     "$databases/blastn.nt.vi.2025_01_12"
      name:   "nt.vi.2025_01_12"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.nt.vi.2025_01_12.tar.gz"
   blastn.refseq.abv:
      db:     "$databases/blastn.refseq.abv.release228"
      name:   "refseq.abv.release228"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.refseq.abv.release228.tar.gz"
   blastn.refseq.vi:
      db:     "$databases/blastn.refseq.vi.release228"
      name:   "refseq.vi.release228"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.refseq.vi.release228.tar.gz"
   blastp.uniref100.abv:
      db:     "$databases/blastp.uniref100.abv.2024_11_27"
      name:   "uniref100.abv.2024_11_27"
      search: "blastp"
      url:    "https://a3s.fi/lazypipe-db/blastp.uniref100.abv.2024_11_27.tar.gz"
   blastp.uniref100.vi:
      db:     "$databases/blastp.uniref100.vi.2024_11_27"
      name:   "uniref100.vi.2024_11_27"
      search: "blastp"
      url:    "https://a3s.fi/lazypipe-db/blastp.uniref100.vi.2024_11_27.tar.gz"
   diamondx.uniref100.abv:
      db:     "$databases/diamond.uniref100.abv.2024_11_27.dmnd"
      name:   "uniref100.abv.2024_11_27"
      search: "diamondx"
      url:    "https://a3s.fi/lazypipe-db/diamond.uniref100.abv.2024_11_27.dmnd.tar.gz"
   diamondx.uniref100.vi:
      db:     "$databases/diamond.uniref100.vi.2024_11_27.dmnd"
      name:   "uniref100.vi.2024_11_27"
      search: "diamondx"
      url:    "https://a3s.fi/lazypipe-db/diamond.uniref100.vi.2024_11_27.dmnd.tar.gz"
   diamondp.uniref100.abv:
      db:     "$databases/diamond.uniref100.abv.2024_11_27.dmnd"
      name:   "uniref100.abv.2024_11_27"
      search: "diamondp"
      url:    "https://a3s.fi/lazypipe-db/diamond.uniref100.abv.2024_11_27.dmnd.tar.gz"
   diamondp.uniref100.vi:
      db:     "$databases/diamond.uniref100.vi.2024_11_27.dmnd"
      name:   "uniref100.vi.2024_11_27"
      search: "diamondp"
      url:    "https://a3s.fi/lazypipe-db/diamond.uniref100.vi.2024_11_27.dmnd.tar.gz"
   blastn.rdp:
      db:     "$databases/blastn.rdp_16S_trainset19"
      name:   "rdp_16S_trainset19"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.rdp_16S_trainset19.tar.gz"
   blastn.silva:
      db:     "$databases/blastn.SILVA_138.2_SSURef"
      name:   "SILVA_138.2_SSURef"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.SILVA_138.2_SSURef.tar.gz"
   minimap.silva:
      db:     "$databases/SILVA_138.2_SSURef.fasta"
      name:   "SILVA_138.2_SSURef"
      search: "minimap"
      url:    "https://a3s.fi/lazypipe-db/minimap.SILVA_138.2_SSURef.tar.gz"
   blastn.silva.nr99:
      db:     "$databases/blastn.SILVA_138.2_SSURef_NR99"
      name:   "SILVA_138.2_SSURef_NR99"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/blastn.SILVA_138.2_SSURef_NR99.tar.gz"
   hmmscan.pfam.vi:
      db:     "$databases/hmm.pfam.vi.2024_05"
      name:   "pfam.vi.2024_05"
      search: "hmmscan"
      url:    "https://a3s.fi/lazypipe-db/hmm.pfam.vi.2024_05.tar.gz"
   hmmscan.rdrp:
      db:     "$databases/hmm.NeoRdRp.2.1"
      name:   "NeoRdRp.2.1"
      search: "hmmscan"
      url:    "https://a3s.fi/lazypipe-db/hmm.NeoRdRp.2.1.tar.gz"
   sans:
      db:     "sans"
      name:   "UniProtKB"
      search: "sans"
   blastn.ictv:
      db:     "$databases/ictv.MSL40.v1"
      name:   "ICTV MSL40.v1 E+A"
      search: "blastn"
      url:    "https://a3s.fi/lazypipe-db/ictv.MSL40.v1.tar.gz"
   blastp.ictv:
      db:     "$databases/ictv.MSL40.v1.prot"
      name:   "ICTV MSL40.v1 E+A"
      search: "blastp"
      url:    "https://a3s.fi/lazypipe-db/ictv.MSL40.v1.prot.tar.gz"
   blastp.nr:
      db:     "$databases/nr_cluster_seq.vi.v20251006"
      name:   "BLAST index for nr_cluster_seq v20251006"
      search: "blastp"
      url:    "https://a3s.fi/lazypipe-db/nr_cluster_seq.vi.v20251006.tar.gz"      
      

# ANNOTATION STRATEGIES: call with --anns strategy
ann.strategies:
    # virus only:
    vi.nt:             "--ann1 minimap.nt.vi --ann2 vi:blastn.nt.abv"
    vi.nt.env:         "--ann1 minimap.nt.vi --ann2 vi:blastn.nt"
    vi.nt.fast:        "--ann1 minimap.nt.vi"
    vi.extend:         "--ann1 minimap.nt.vi,sans --ann2 vi:blastn.nt.abv,vi:blastp.uniref100.abv"
    vi.refseq:         "--ann1 minimap.refseq.vi --ann2 vi:blastn.refseq.abv"
    vi.refseq.fast:    "--ann1 minimap.refseq.vi"
    vi.chain1:         "--ann1 minimap.nt.abv,blastn.nt.abv,blastp.uniref100.abv"
    vi.chain2:         "--ann1 minimap.nt.abv,blastp.uniref100.abv"
    vi.chain3:         "--ann1 minimap.nt.abv,diamondp.uniref100.abv"
    vi.chain4:         "--ann1 minimap.nt.abv,sans"
    vi.chain1.env:     "--ann1 minimap.nt,blastn.nt.abv,blastp.uniref100.abv"
    vi.chain3.env:     "--ann1 minimap.nt,diamondp.uniref100.abv"
    chain1.env:    "--ann1 minimap.nt,blastn.nt.abv,blastp.uniref100.abv"
    chain3.env:    "--ann1 minimap.nt,diamondp.uniref100.abv"
    # archaea+bacteria+viruses
    abv.nt:            "--ann1 minimap.nt.abv --ann2 vi:blastn.nt.abv,ab:blastn.nt.abv"
    abv.nt.fast:       "--ann1 minimap.nt.abv"
    abv.extend:        "--ann1 minimap.nt.abv,sans --ann2 vi:blastn.nt.abv,ab:blastn.nt.abv,vi:blastp.uniref100.abv,ab:blastp.uniref100.abv"

# GENOMES FOR HOST/CONTAMINATION FILTERING
host.databases:
   Aedes_aegypti:
      accession:  "GCF_002204515.2"
      db:         "$hostgenomes/GCF_002204515.2_genomic+rna.fna.gz"
      name:       "Aedes aegypti genomic+rna"
      latinName:  "Aedes aegypti"
      commonName: "Yellow fever mosquito"
      taxid:      "7159"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_002204515.2_genomic+rna.tar.gz"
   Aedes_albopictus:
      accession:  "GCF_035046485.1"
      db:         "$hostgenomes/GCF_035046485.1_genomic+rna.fna.gz"
      name:       "Aedes albopictus genomic+rna"      
      latinName:  "Aedes albopictus"
      commonName: "Asian tiger mosquito"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_035046485.1_genomic+rna.tar.gz"
   Chlorocebus_aethiops:
      accession:  "GCA_023783515.1"
      db:         "$hostgenomes/GCA_023783515.1_genomic.fna.gz"
      latinName:  "Chlorocebus aethiops"
      commonName: "Grivet monkey"
      taxid:      "9534"
      url:        "https://a3s.fi/lazypipe-hostgen/GCA_023783515.1_genomic.tar.gz"
   Culex_pipiens_pallens:
      accession:   "GCF_016801865.2"
      db:          "$hostgenomes/GCF_016801865.2_genomic+rna.fna.gz"
      name:        "Culex pipiens pallens genomic+rna"
      latinName:   "Culex pipiens pallens"
      commonName:  "Northern house mosquito"
      url:         "https://a3s.fi/lazypipe-hostgen/GCF_016801865.2_genomic+rna.tar.gz"
   Culex_laticinctus:
      accession:   "GCA_964187845.1"
      db:          "$hostgenomes/GCA_964187845.1_genomic.fna.gz"
      name:        "Culex laticinctus genomic+rna"
      latinName:   "Culex laticinctus"
      commonName:  "mosquito"
      url:         "https://a3s.fi/lazypipe-hostgen/GCA_964187845.1_genomic.tar.gz"      
   Bos_taurus:
      accession:  "GCF_002263795.3"
      db:         "$hostgenomes/GCF_002263795.3_genomic+rna.fna.gz"
      name:       "Cattle genomic+rna"
      commonName: "Cattle"
      latinName:  "Bos taurus"
      taxid:      "9913"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_002263795.3_genomic+rna.tar.gz"
   Canis_lupus_fam:
      accession:  "GCF_011100685.1"
      db:         "$hostgenomes/GCF_011100685.1_genomic+rna.fna.gz"
      name:       "Dog genomic+rna"
      latinName:  "Canis lupus familiaris"
      commonName: "Dog"
      taxid:      "9615"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_011100685.1_genomic+rna.tar.gz"
   Equus_caballus:
      accession:  "GCF_002863925.1"
      db:         "$hostgenomes/GCF_002863925.1_genomic+rna.fna.gz"
      name:       "Horse genomic+rna"
      latinName:  "Equus caballus"
      commonName: "Horse"
      taxid:      "9796"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_002863925.1_genomic+rna.tar.gz"
   Felis_catus:
      accession:  "GCF_018350175.1"
      db:         "$hostgenomes/GCF_018350175.1_genomic+rna.fna.gz"
      name:       "Cat genomic+rna"
      latinName:  "Felis catus"
      commonName: "Cat"
      taxid:      "9685"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_018350175.1_genomic+rna.tar.gz"
   Homo_sapiens:
      accession:  "GCF_000001405.40"
      db:         "$hostgenomes/GCF_000001405.40_genomic+rna.fna.gz"
      name:       "Human genomic+rna"
      latinName:  "Homo sapiens"
      commonName: "Human"
      taxid:      "9606"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_000001405.40_genomic+rna.tar.gz"
   Macaca_mulatta:
      accession:  "GCA_003339765.3"   
      db:         "$hostgenomes/GCA_003339765.3_genomic+rna.fna.gz"
      name:       "Rhesus macaque genomic+rna"
      latinName:  "Macaca mulatta"
      commonName: "Rhesus macaque"
      taxid:      "9544"
      url:        "https://a3s.fi/lazypipe-hostgen/GCA_003339765.3_genomic+rna.tar.gz"
   Mus_musculus:
      accession:  "GCF_000001635.27"
      db:         "$hostgenomes/GCF_000001635.27_genomic+rna.fna.gz"
      name:       "Mouse genomic+rna"
      latinName:  "Mus musculus"
      commonName: "House mouse"
      taxid:      "10090"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_000001635.27_genomic+rna.tar.gz"
   Myodes_glareolus:
      accession:  "GCF_902806735.1"
      db:         "$hostgenomes/GCF_902806735.1_genomic+rna.fna.gz"
      name:       "Bank vole genomic+rna"
      latinName:  "Myodes glareolus"
      commonName: "Bank vole"
      taxid:      "447135"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_902806735.1_genomic+rna.tar.gz"
   Myotis_daubentonii:
      accession:  "GCF_963259705.1"
      db:         "$hostgenomes/GCF_963259705.1_genomic+rna.fna.gz"
      name:       "Daubentons bat genomic+rna"
      latinName:  "Myotis daubentonii"
      commonName: "Daubentons bat"
      taxid:      "98922"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_963259705.1_genomic+rna.tar.gz"
   Neovison_vison:
      accession:  "GCF_020171115.1"
      db:         "$hostgenomes/GCF_020171115.1_genomic+rna.fna.gz"
      name:       "American mink genomic+rna"
      latinName:  "Neovison vison"
      commonName: "American mink"
      taxid:      "452646"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_020171115.1_genomic+rna.tar.gz"
   Ovis_aries:
      accession:  "GCF_016772045.2"
      db:         "$hostgenomes/GCF_016772045.2_genomic+rna.fna.gz"
      name:       "Sheep genomic+rna"
      latinName:  "Ovis aries"
      commonName: "Sheep"
      taxid:      "9940"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_016772045.2_genomic+rna.tar.gz"
   Rattus_norvegicus:
      accession:  "GCF_036323735.1"
      db:         "$data/hostgen/GCF_036323735.1_genomic+rna.fna.gz"
      name:       "Norwegian rat genomic+rna"
      latinName:  "Rattus norvegicus"
      commonName: "Rat"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_036323735.1_genomic+rna.tar.gz"
   Sorex_araneus:
      accession:  "GCF_027595985.1"
      db:         "$hostgenomes/GCF_027595985.1_genomic+rna.fna.gz"
      name:       "European shrew genomic+rna"
      latinName:  "Sorex araneus"
      commonName: "European shrew"
      taxid:      "42254"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_027595985.1_genomic+rna.tar.gz"
   Sus_scrofa:
      accession:  "GCF_000003025.6"
      db:         "$hostgenomes/GCF_000003025.6_genomic+rna.fna.gz"
      name:       "pig genomic+rna"
      latinName:  "Sus scrofa"
      commonName: "pig"
      taxid:      "9823"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_000003025.6_genomic+rna.tar.gz"
   Vulpes_lagopus:
      accession:  "GCF_018345385.1"
      db:         "$hostgenomes/GCF_018345385.1_genomic+rna.fna.gz"
      name:       "Arctic fox genomic+rna"
      latinName:  "Vulpes lagopus"
      commonName: "Arctic fox"
      taxid:      "494514"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_018345385.1_genomic+rna.tar.gz"
   Ixodes_scapularis:
      accession:  "GCF_016920785.2"
      db:         "$hostgenomes/GCF_016920785.2_genomic+rna.fna.gz"
      name:       "black-legged tick genomic+rna"
      latinName:  "Ixodes scapularis"
      commonName: "black-legged tick"
      taxid:      "6945"
      url:        "https://a3s.fi/lazypipe-hostgen/GCF_016920785.2_genomic+rna.tar.gz"
   Ixodes_persulcatus:
      accession:   "GCA_013358835.2"
      db:          "$hostgenomes/GCA_013358835.2_genomic+rna.fna.gz"
      name:        "Taiga tick genomic+rna"
      latinName:   "Ixodes persulcatus"
      commonName:  "taiga tick"
      taxid:       "34615"
      url:         "https://a3s.fi/lazypipe-hostgen/GCA_013358835.2_genomic+rna.tar.gz"
   Chrysops_caecutiens:
      accession:  "GCA_963971475.1"
      db:         "$hostgenomes/GCA_963971475.1_genomic.fna.gz"
      name:       "Horse fly genomic"
      latinName:  "Chrysops caecutiens"
      commonName: "Horse fly"
      url:        "https://a3s.fi/lazypipe-hostgen/GCA_963971475.1_genomic.tar.gz"

taxonomy:
   db:            "$data/taxonomy"
   name:          "NCBI taxonomy"
   update:        0 # 1 => update, 0 => don't update
   update_time:   5 # in days
   url:           "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"

   
ICTV.VMR:
   db:            "/scratch/project_2003755/taxonomy/ICTV/VMR_MSL40.v1.20250307.tsv"
   name:          "ICTV VMR tables"
   url:           "https://ictv.global/sites/default/files/VMR/VMR_MSL40.v1.20250307.xlsx"

