#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);

# 
# Prints stats for an assembly
my $usage= "\nUSAGE: $0 --format|f format --reads reads.fq --reads_flt reads.flt.fq --reads_hgflt reads.hgflt.fq ".
           "            --cont contigs.fa --idx contigs.idxstats --orfs ORFs.fa\n\n".
	   "reads       [file] : fastq file containing the original reads. Can be gziped.\n".
	   "reads_flt   [file] : fastq file containing trimmed reads.\n".
	   "reads_hgflt [file] : fastq file containing hostgenome filtered reads.\n".
	   "cont        [file] : fasta file containing contigs.\n".
	   "idx         [file] : text file generated by the samtools idxstats for bam file mapping reads to contigs\n".
	   "orfs        [file] : fasta file containing nt ORF sequences\n".
	   "\n".
	   "format [str]  : col|row[,names,%], default \'row,names\'\n".
	   "      col     : stats printed in a single column\n".
	   "      row     : stats printed in a single row\n".
	   "      names   : in col format will print metric names in the first column and values in the second\n".
	   "                in row format will print header row with metric names\n".
	   "      %       : print stats in percents\n".
	   "\n".
	   "printed statistics:\n".
	   "reads         : number of read pairs in unfiltered library\n".
	   "reads.flt     : number of read pairs in filtered library\n".
	   "reads.hgflt   : number of read pairs in host-genome filtered library\n".
	   "reads.contigs : number of read pairs mapped to contigs\n".
	   "contigs       : number of contigs\n".
	   "orfs          : number of genes\n".
	   "\n";
	   
my $format				= "row,names";
my $reads_fa 			= !1;
my $reads_flt_fa		= !1;
my $reads_hgflt_fa		= !1;
my $contigs_fa			= !1;
my $orfs_fa 			= !1;
my $idxstats			= !1;
GetOptions(	'format|f=s' 	=> \$format,
		'reads=s'			=> \$reads_fa,
		'reads_flt=s'		=> \$reads_flt_fa,
		'reads_hgflt=s'		=> \$reads_hgflt_fa,
		'contigs|cont=s'	=> \$contigs_fa,
		'orfs=s'			=> \$orfs_fa,
		'idxstats|idx=s'	=> \$idxstats) or die $usage;

# CHECK INPUT
if( !($format =~m/(row|col)/ig) ){
	print STDERR "\ninvalid format: $format\n";
	die $usage;
}
if( !$reads_flt_fa || !$contigs_fa || !$orfs_fa || !$idxstats){
	print STDERR "\nmissing arguments\n";
	die $usage;
}
if( !$reads_fa ){
	$reads_fa 		= $reads_flt_fa;
}
if( !$reads_hgflt_fa){
	$reads_hgflt_fa = $reads_flt_fa;
}

if( !(-e $reads_fa) )   		{ die "$0: missing file: $reads_fa\n";}
if( !(-e $reads_flt_fa) )   	{ die "$0: missing file: $reads_flt_fa\n";}
if( !(-e $reads_hgflt_fa) )   	{ die "$0: missing file: $reads_hgflt_fa\n";}
if( !(-e $contigs_fa) )			{ die "$0: missing file: $contigs_fa\n";}
if( !(-e $orfs_fa) )  			{ die "$0: missing file: $orfs_fa\n";}
if( !(-e $idxstats) )			{ die "$0: missing file: $idxstats";}


# printing headers
my @headers;
push(@headers,('reads','reads.flt','reads.hgflt','reads.contigs','contigs','orfs'));
my %stats_hash;
foreach my $h(@headers){ $stats_hash{$h} = 0;}

	# reads
$stats_hash{'reads'} 		= ($reads_fa =~ m/\.gz$/ )? ((`gunzip -c $reads_fa | wc -l`)/4) : (`cat $reads_fa | wc -l`)/4;
	# reads.flt
$stats_hash{'reads.flt'} 	= ($reads_flt_fa =~ m/\.gz$/ )? ((`gunzip -c $reads_flt_fa | wc -l`)/4) : (`cat $reads_flt_fa | wc -l`)/4;
	# reads.hgflt
$stats_hash{'reads.hgflt'} 	= ($reads_hgflt_fa =~ m/\.gz$/ )? ((`gunzip -c $reads_hgflt_fa | wc -l`)/4) :(`cat $reads_hgflt_fa | wc -l`)/4;

	# reads.contigs
open(IN, "<$idxstats") or die "failed to open: $idxstats\n";
while(my $l=<IN>){
	chomp($l);
	my ($contig,$length,$mapped,$unmapped)= split(/\t/,$l,-1);
	$stats_hash{'reads.contigs'} 	+= $mapped;
}
close(IN);

	# contigs
$stats_hash{'contigs'}	= (`grep -c "^>" $contigs_fa`)/1;
	# ORFs
$stats_hash{'orfs'}		= (`grep -c "^>" $orfs_fa`)/1;


	# CREATE PERCENTAGES
if( ($format =~ m/(\%)/) ){
	$stats_hash{'reads.flt'} 		= $stats_hash{'reads.flt'} / $stats_hash{'reads'} *100;
	$stats_hash{'reads.hgflt'}		= $stats_hash{'reads.hgflt'} / $stats_hash{'reads'} *100;
	$stats_hash{'reads.contigs'}	= $stats_hash{'reads.contigs'} / $stats_hash{'reads'} *100;
	$stats_hash{'reads'}	 		= 100;
}


	# PRINTING
if( $format =~ m/(row)/i ){
	if( ($format =~ m/(names)/i) ){
		print "",join("\t",@headers),"\n";
	}
	print $stats_hash{$headers[0]};
	for(my $i=1; $i<scalar(@headers); $i++){
		print "\t",$stats_hash{$headers[$i]};
	}
	print "\n";
}
else{
	if( ($format =~ m/(names)/i) ){
		for(my $i=0; $i<scalar(@headers); $i++){
			print $headers[$i],"\t",$stats_hash{$headers[$i]},"\n";
		}
	}
	else{
		for(my $i=0; $i<scalar(@headers); $i++){
			print $stats_hash{$headers[$i]},"\n";
		}
	}
}

